<h2>Matrix</h2>
<p>Python can solve different matrix manipulations and operations. Numpy Module provides different methods for matrix operations.</p>
<ol>
    <li><b>add()</b> − Add elements of two matrices.</li>
    <li><b>subtract()</b> − Subtract elements of two matrices.</li>
    <li><b>multiply()</b> − Multiply elements of two matrices.</li>
    <li><b>divide()</b> − Divide elements of two matrices.</li>    
    <li><b>sqrt()</b> − Square root of each element of matrix.</li>
    <li><b>dot()</b> − It performs matrix multiplication, does not element wise multiplication.</li>    
    <li><b>sum(x, axis)</b> − Add to all the elements in matrix. <br/>Second argument is optional, it is used when we want to compute the column sum if axis is 0 and row sum if axis is 1.</li>
    <li><b>T</b> − It performs transpose of the specified matrix.</li>
</ol>

In [1]:
import numpy

<h3>Matrix Addition</h3>

<img src="http://jegan.my/jupyter/matrixaddition.jpg"/>

In [2]:
x = numpy.array([[4, 8], [3, 7]])
x

array([[4, 8],
       [3, 7]])

In [3]:
y = numpy.array([[1, 0], [5, 2]])
y

array([[1, 0],
       [5, 2]])

In [4]:
numpy.add(x,y)

array([[5, 8],
       [8, 9]])

<h3>Matrix Subtraction</h3>

<img src="http://jegan.my/jupyter/subtraction.jpg"/>

In [5]:
x = numpy.array([[1, 2], [3, 4]])
x

array([[1, 2],
       [3, 4]])

In [6]:
y = numpy.array([[1, 3], [5, 5]])
y

array([[1, 3],
       [5, 5]])

In [7]:
numpy.subtract(x,y)

array([[ 0, -1],
       [-2, -1]])

<h3>Matrix - Elements Multiplication</h3>

<img src="http://jegan.my/jupyter/multiply.jpg"/>

In [8]:
x = numpy.array([[1, 2], [3, 4]])
x

array([[1, 2],
       [3, 4]])

In [9]:
y = numpy.array([[5, 5], [5, 5]])
y

array([[5, 5],
       [5, 5]])

In [10]:
numpy.multiply(x,y)

array([[ 5, 10],
       [15, 20]])

<h3>Matrix - Elements Division</h3>

<img src="http://jegan.my/jupyter/divide.jpg"/>

In [11]:
x = numpy.array([[9, 15], [24, 8]])
x

array([[ 9, 15],
       [24,  8]])

In [12]:
y = numpy.array([[3, 5], [8, 2]])
y

array([[3, 5],
       [8, 2]])

In [13]:
numpy.divide(x, y)

array([[3., 3.],
       [3., 4.]])

<h3>Matrix - Elements SQRT</h3>

In [14]:
numpy.sqrt(x)

array([[3.        , 3.87298335],
       [4.89897949, 2.82842712]])

<h3>Matrix - Sum of all elements in the Matrix</h3>

In [15]:
x = numpy.array([[5, 10], [15, 20]])
x

array([[ 5, 10],
       [15, 20]])

In [16]:
numpy.sum(x)

50

In [17]:
numpy.sum(x, axis=0)

array([20, 30])

In [18]:
numpy.sum(x, axis=1)

array([15, 35])

<h3>Matrix Multiplication</h3>

<img src="http://jegan.my/jupyter/matrixmultiplication.jpg"/>

In [19]:
x = numpy.array([[3, 4], [2, 1]])
x

array([[3, 4],
       [2, 1]])

In [20]:
y = numpy.array([[1, 5], [3, 7]])
y

array([[1, 5],
       [3, 7]])

In [21]:
numpy.dot(x,y)

array([[15, 43],
       [ 5, 17]])

<h3>Matrix - Transpose</h3>

In [22]:
x = numpy.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])
x

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [23]:
x.T

array([[ 5, 20, 35],
       [10, 25, 40],
       [15, 30, 45]])

<h3>Matrix - Inverse</h3>

In [24]:
x = numpy.array([[4, 3], [3, 2]]) 
x

array([[4, 3],
       [3, 2]])

In [25]:
y = numpy.linalg.inv(x)
y

array([[-2.,  3.],
       [ 3., -4.]])

In [26]:
numpy.dot(x, y)

array([[1., 0.],
       [0., 1.]])

<b>Note:</b> When a matrix is multiplied with its Inverse the result is Identity Matrix

<h3>Matrix Division</h3>

<p>
    In Matrix there is no concept of Division. But we can multiply by an inverse, which achieves the same thing.
</p><br/>
<b>A/B = A * (1/B) = A * B<sup>-1</sup></b><br/>
<b>A/B = C</b>

In [27]:
a = numpy.array([[3, -2], [4, -3]])
a

array([[ 3, -2],
       [ 4, -3]])

In [28]:
b = numpy.array([[6, -10], [1, -2]])
b

array([[  6, -10],
       [  1,  -2]])

In [29]:
binverse = numpy.linalg.inv(b)
binverse

array([[ 1. , -5. ],
       [ 0.5, -3. ]])

In [30]:
result = numpy.dot(a, binverse)
result

array([[  2. ,  -9. ],
       [  2.5, -11. ]])