# NumPy Flatten

## Flatten
Flatten function return a copy of the array collapsed into one dimension. Let's see with some examples:

In [2]:
import numpy as np

In [3]:
x = np.array([[2,3], [4,5]])
x.flatten()

array([2, 3, 4, 5])

Flatten function takes order as parameter. The value of order can be C, F, A and K

<ol>
<li>'C' means to flatten in row-major (C-style) order. </li>
<li>'F' means to flatten in column-major (Fortran- style) order. </li>
<li>'A' means to flatten in column-major order if a is Fortran contiguous in memory, row-major order otherwise. </li>
<li>'K' means to flatten a in the order the elements occur in memory. </li>
</ol>

The default is 'C'. 

In [5]:
x.flatten('C')

array([2, 3, 4, 5])

<img src="https://www.w3resource.com/w3r_images/numpy-manipulation-ndarray-flatten-function-image-1.png" width="200"/>

In [6]:
x.flatten('F')

array([2, 4, 3, 5])

<img src="https://www.w3resource.com/w3r_images/numpy-manipulation-ndarray-flatten-function-image-2.png" width="200"/>

In [9]:
x.flatten('A')

array([2, 3, 4, 5])

In [10]:
x.flatten('K')

array([2, 3, 4, 5])